module.exports = {
    gettemp: 	  require('./gettemp'),
    settemp: 	  require('./settemp'),
    bedtemp: 	  require('./bedtemp'),
    cooldown: 	require('./cooldown'),
   	home: 	 	  require('./home'),
    move:       require('./move'),
    extrude:    require('./extrude'),
    reverse:    require('./reverse'),
   	print: 		  require('./print'),
   	pause: 		  require('./pause'),
   	reset: 	    require('./reset'),
   	off: 		    require('./off'),
   	monitor: 	  require('./monitor'),
   	monitor: 	  require('./monitor2'),
   	connect: 	  require('./connect'),
    connect2:   require('./customconnect'), 
   	disconnect: require('./disconnect'),
   	resume: 	  require('./resume'),
   	exit: 		  require('./exit'),
   	ls: 		    require('./ls'),
    sdprint:    require('./sdprint'),
}